apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-1 # Nome vai ser usado no pod para que o container consiga se comunicar 
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: standard