apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: slow
provisioner: kubernetes.io/gce-pd # esse campo muda de acordo com o clound que esta subindo  
parameters:
  type: pd-standard
  fstype: ext4