apiVersion: apps/v1
kind: Deployment
metadata:
  name: portal-noticias-deployment
spec:
  template:
    metadata:
      name: portal-noticias
      labels:
        app: portal-noticias
    spec:
      containers:
        - name: portal-noticias-container
          image: aluracursos/portal-noticias:1  
          ports:
            - containerPort: 80
          envFrom:
            - configMapRef:
                name: portal-configmap 
          livenessProbe:
            httpGet:
              path: / # caminho do  metodo que ele vai testar
              port: 80
            periodSeconds: 10   # periodo que ele vai fazer os teste
            failureThreshold: 3 # quantas falas ele vai permitir
            initialDelaySeconds: 20 # tempo que ele vai demorar para fazer o primeiro teste quando a aplicação subir  
          readnessProbe:
            httpGet:
              path: / # caminho do  metodo que ele vai testar
              port: 80
            periodSeconds: 10   # periodo que ele vai fazer os teste
            failureThreshold: 5 # quantas falas ele vai permitir
            initialDelaySeconds: 3 # tempo que ele vai demorar para fazer o primeiro teste quando a aplicação subir      
  replicas: 3
  selector:
    matchLabels:
      app: portal-noticias                    